server:
  port: 8040
spring:
  #出现错误时, 直接抛出异常
  mvc.throw-exception-if-no-handler-found: true
  #不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false
  resource:
    static-locations: classpath:/static/,classpath:/public/,classpath:/templates/
  session:
    timeout: -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: shop-web-feign
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: ENC(+M1iPAjZnE4mZNCaO4j0pHmzQI4vfJdBuGzdC5ybFHpzIk51BBhfXg==) # 访问身份验证中用到用户标识
    accessKeySecret: ENC(Cl5q2unbLihtEgxPkVnuE1TVckT0X+oxRdhLk92h04cI73zaVxE4ag==) # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: dinner-sys # oss的存储空间
    prefix: dinner/goods


# 配置文件加密key
jasypt:
  encryptor:
    password: dinner-sys

# JWT
jwt:
  issuer: dinner-sys