server:
  port: 8040
spring:
  #出现错误时, 直接抛出异常
  mvc.throw-exception-if-no-handler-found: true
  #不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false
  resource:
    static-locations: classpath:/static/,classpath:/public/,classpath:/templates/
  session:
    timeout: -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: shop-web-feign
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: '{cipher}d62b7ff60a773855a8db9606c40e13542e6bd55d094de76c58d2da57f8d682a6f476e8424783a6db1f7c8306ec0202cc' # 访问身份验证中用到用户标识
    accessKeySecret: '{cipher}c3bf973adc0d4d39b6152c9eff8a1a8a38d948e7867e73dad1f7a7799683f9f17b05203efc64192e093aa586541595b3'  # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: dinner-sys # oss的存储空间
    prefix: dinner/goods


# 配置文件加密key
jasypt:
  encryptor:
    password: dinner-sys

# JWT
jwt:
  issuer: dinner-sys

dinner:
  sys:
    appUrl: http://dinner.natapp1.cc