server:
  port: 8060
spring:
  #出现错误时, 直接抛出异常
  mvc.throw-exception-if-no-handler-found: true
  #不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false
  resource:
    static-locations: classpath:/static/,classpath:/public/,classpath:/templates/
  session:
    timeout: -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: wx-mp-app
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# 配置文件加密key
jasypt:
  encryptor:
    password: dinner-sys

# JWT
jwt:
  issuer: dinner-sys
